spring:
  application:
    name: family-account-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 15755018404
    url: jdbc:mysql://localhost:3306/FAMACT?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
server:
  port: 8088
logging:
  level:
    com.gk.api.moudle: debug
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true